# Site settings
title: LambdaCD - Build Pipelines as Code
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  LambdaCD is a toolbox to enable you to build your own buildserver.
  It's it's a continuous delivery pipeline, in code
  It's your own custom built Jenkins/Go/TeamCity/..., in Clojure
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lambda.cd" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "api-docs/**/*"
    values:
      sitemap:         false
